### ISSUE TITLE
Implement pagination

### ISSUE THREAD

**Issue by jesseclay** [ipfs/get-gh-contributors#4]
Didn't see any way to paginate API results, am I just missing it? Otherwise, can we get this functionality.

**Comment by daviddias** [comment]
Pagination for you, Sir - https://github.com/ipfs/get-gh-contributors/commit/4d400a20ed59d85360d19d9efce8b64e628a99a9

**Comment by daviddias** [comment]
![image](https://cloud.githubusercontent.com/assets/1211152/23796065/b381a1fa-0590-11e7-9fee-1fe72473cacb.png)

It also gives you an error if you go out of bounds
