### ISSUE TITLE
Deploy the app

### ISSUE THREAD

**Issue by daviddias** [ipfs/get-gh-contributors#5]
I've deployed the app and the container shows it is running:

```
# ...
=====> Application deployed:
http://contributors.cloud.ipfs.team
```

```
2017-03-10T13:22:13.500444850Z app[web.1]:
2017-03-10T13:22:13.500520340Z app[web.1]: > get-gh-contributors@1.0.0 start /app
2017-03-10T13:22:13.500529307Z app[web.1]: > node src/api/start.js
2017-03-10T13:22:13.500535449Z app[web.1]:
2017-03-10T13:22:14.250589424Z app[web.1]: API has started http://localhost:5000
```

However, I keep getting 502 on the reverse proxy http://contributors.cloud.ipfs.team/

@lgierth any thoughts? Nothing seems unusual, not sure if there was a change in how all this is configured in the backend.

To deploy https://github.com/ipfs/get-gh-contributors#deploy.

Once we have this in place, a request from @jesseclay: Can we have `ipfs.io/contributors` point to `contributors.cloud.ipfs.team/contributors`?

**Comment by victorb** [comment]
@diasdavid seems you're listning on `localhost` instead of `0.0.0.0` which means it'll only accept local connections. Try binding it to `0.0.0.0` instead and deploy again.

**Comment by ghost** [comment]
also make sure the procfile picks up $PORT (it might already)

**Comment by ghost** [comment]
> Can we have ipfs.io/contributors point to contributors.cloud.ipfs.team/contributors?

I'm not sure I brought it up loudly enough, but it'd *greatly simplify things* if the contributors were static, and would be updated by running get-gh-contributors every once in a while. Having no server part is a huge win.

**Comment by ghost** [comment]
It also currently lacks instrumentation which is a blocker for production deployment.

**Comment by daviddias** [comment]
> @diasdavid seems you're listening on localhost instead of 0.0.0.0

Hm.. dokku should put the host on `process.env.HOST`, seems that it isn't, though. Works now http://contributors.cloud.ipfs.team/contributors?org=all \o/

@jesseclay you can use it [now](http://contributors.cloud.ipfs.team/contributors?org=all) :) 

@lgierth I brought that up too a couple of times, but it seems that pagination is an important feature (as the contributors list tends to increase)
