### ISSUE TITLE
De-duplicate contributors in /all call

### ISSUE THREAD

**Issue by jesseclay** [ipfs/get-gh-contributors#6]
When requesting all contributors across all projects, can we de-duplicate them? Currently the call to `/contributors?org=all` returns a bunch of duplicate contributors (b/c these people have contributed to multiple IPFS repos).

My current use case: I want to graphically list all contributors across all repos, but I don't want to see duplicate listings. Knowing the specific repository contributed to isn't that important, but could be useful in the future. Maybe the best return would be adding in an array per user?

```
{
"url": "https://github.com/jbenet",
"photo": "https://avatars.githubusercontent.com/u/138401?v=3",
"username": "jbenet",
"repositories": ["libp2p", "go-ipfs", "js-ipfs", "polar-bear-ipfs"]
}
```

If that's too much trouble then just straight up only listing the contributor once would be best.

**Comment by daviddias** [comment]
Shipped and deployed.

```
» curl "http://contributors.cloud.ipfs.team/contributors?org=all" | json | grep diasdavid

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39532  100 39532    0     0  80303      0 --:--:-- --:--:-- --:--:-- 80186
    "url": "https://github.com/diasdavid",
    "username": "diasdavid"
```

I'll come back to add that "repositories" field if that is really used. Note that you can still pick users by org.

**Comment by jesseclay** [comment]
amazing that was soopa fast
