### ISSUE TITLE
Serve API over https

### ISSUE THREAD

**Issue by jesseclay** [ipfs/get-gh-contributors#7]
Getting this error when loading from an https site, need API to be served over HTTPS:

![image](https://cloud.githubusercontent.com/assets/1719763/24396405/f5f2d30e-1357-11e7-93b5-c93dc1ee15bb.png)

**Comment by daviddias** [comment]
@lgierth can we get a TLS Cert for cloud.ipfs.team and everything underneath?

**Comment by daviddias** [comment]
Also opened a ticket for you https://github.com/ipfs/ops-requests/issues/52 :) following `The Process™`

**Comment by ghost** [comment]
If I'm going to put work into the contributors thing, I'll rather spend it on making it static as suggested in the past. We don't need a webservice serving github contributors to the website. :)

(Obviously still need to get an SSL cert)

**Comment by jesseclay** [comment]
Will still need to have the TLS cert either way though.

Suggest we start certs, then change over to static loading after?

2017-03-28 6:48 GMT-07:00 Lars Gierth <notifications@github.com>:

**Comment by ghost** [comment]
Got a cert
